/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CollectionWhereUniqueInput } from "../../collection/base/CollectionWhereUniqueInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { UserCreateNestedManyWithoutItemsInput } from "./UserCreateNestedManyWithoutItemsInput";
import { TransactionCreateNestedManyWithoutItemsInput } from "./TransactionCreateNestedManyWithoutItemsInput";
@InputType()
class ItemCreateInput {
  @ApiProperty({
    required: false,
    type: () => CollectionWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CollectionWhereUniqueInput)
  @IsOptional()
  @Field(() => CollectionWhereUniqueInput, {
    nullable: true,
  })
  collection?: CollectionWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  metadata?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserCreateNestedManyWithoutItemsInput,
  })
  @ValidateNested()
  @Type(() => UserCreateNestedManyWithoutItemsInput)
  @IsOptional()
  @Field(() => UserCreateNestedManyWithoutItemsInput, {
    nullable: true,
  })
  owner?: UserCreateNestedManyWithoutItemsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  tokenId?: string | null;

  @ApiProperty({
    required: false,
    type: () => TransactionCreateNestedManyWithoutItemsInput,
  })
  @ValidateNested()
  @Type(() => TransactionCreateNestedManyWithoutItemsInput)
  @IsOptional()
  @Field(() => TransactionCreateNestedManyWithoutItemsInput, {
    nullable: true,
  })
  transactions?: TransactionCreateNestedManyWithoutItemsInput;
}
export { ItemCreateInput };
