/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CollectionWhereUniqueInput } from "../../collection/base/CollectionWhereUniqueInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { UserUpdateManyWithoutItemsInput } from "./UserUpdateManyWithoutItemsInput";
import { TransactionUpdateManyWithoutItemsInput } from "./TransactionUpdateManyWithoutItemsInput";
@InputType()
class ItemUpdateInput {
  @ApiProperty({
    required: false,
    type: () => CollectionWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CollectionWhereUniqueInput)
  @IsOptional()
  @Field(() => CollectionWhereUniqueInput, {
    nullable: true,
  })
  collection?: CollectionWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  metadata?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserUpdateManyWithoutItemsInput,
  })
  @ValidateNested()
  @Type(() => UserUpdateManyWithoutItemsInput)
  @IsOptional()
  @Field(() => UserUpdateManyWithoutItemsInput, {
    nullable: true,
  })
  owner?: UserUpdateManyWithoutItemsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  tokenId?: string | null;

  @ApiProperty({
    required: false,
    type: () => TransactionUpdateManyWithoutItemsInput,
  })
  @ValidateNested()
  @Type(() => TransactionUpdateManyWithoutItemsInput)
  @IsOptional()
  @Field(() => TransactionUpdateManyWithoutItemsInput, {
    nullable: true,
  })
  transactions?: TransactionUpdateManyWithoutItemsInput;
}
export { ItemUpdateInput };
