/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsString,
  IsOptional,
  IsJSON,
  IsBoolean,
  ValidateNested,
  IsDate,
  IsInt,
  IsEnum,
} from "class-validator";

import { GraphQLJSONObject } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { ItemUpdateManyWithoutCollectionsInput } from "./ItemUpdateManyWithoutCollectionsInput";
import { Type } from "class-transformer";
import { NetworkWhereUniqueInput } from "../../network/base/NetworkWhereUniqueInput";
import { UserUpdateManyWithoutCollectionsInput } from "./UserUpdateManyWithoutCollectionsInput";
import { EnumCollectionProtocolType } from "./EnumCollectionProtocolType";
@InputType()
class CollectionUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  collectionSymbol?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  contractAddress?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  coverImage?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsJSON()
  @IsOptional()
  @Field(() => GraphQLJSONObject, {
    nullable: true,
  })
  customAttributes?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  deletedAt?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  displayImage?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  displayName?: string | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isLogical?: boolean | null;

  @ApiProperty({
    required: false,
    type: () => ItemUpdateManyWithoutCollectionsInput,
  })
  @ValidateNested()
  @Type(() => ItemUpdateManyWithoutCollectionsInput)
  @IsOptional()
  @Field(() => ItemUpdateManyWithoutCollectionsInput, {
    nullable: true,
  })
  items?: ItemUpdateManyWithoutCollectionsInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  listedAt?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => NetworkWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => NetworkWhereUniqueInput)
  @IsOptional()
  @Field(() => NetworkWhereUniqueInput, {
    nullable: true,
  })
  network?: NetworkWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => UserUpdateManyWithoutCollectionsInput,
  })
  @ValidateNested()
  @Type(() => UserUpdateManyWithoutCollectionsInput)
  @IsOptional()
  @Field(() => UserUpdateManyWithoutCollectionsInput, {
    nullable: true,
  })
  owner?: UserUpdateManyWithoutCollectionsInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  platformFeePermyriad?: number | null;

  @ApiProperty({
    required: false,
    enum: EnumCollectionProtocolType,
  })
  @IsEnum(EnumCollectionProtocolType)
  @IsOptional()
  @Field(() => EnumCollectionProtocolType, {
    nullable: true,
  })
  protocolType?: "Erc721" | "Erc1155" | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  royaltyPermyriad?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  royaltyReceiver?: string | null;
}
export { CollectionUpdateInput };
