/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateCollectionArgs } from "./CreateCollectionArgs";
import { UpdateCollectionArgs } from "./UpdateCollectionArgs";
import { DeleteCollectionArgs } from "./DeleteCollectionArgs";
import { CollectionFindManyArgs } from "./CollectionFindManyArgs";
import { CollectionFindUniqueArgs } from "./CollectionFindUniqueArgs";
import { Collection } from "./Collection";
import { ItemFindManyArgs } from "../../item/base/ItemFindManyArgs";
import { Item } from "../../item/base/Item";
import { UserFindManyArgs } from "../../user/base/UserFindManyArgs";
import { User } from "../../user/base/User";
import { Network } from "../../network/base/Network";
import { CollectionService } from "../collection.service";

@graphql.Resolver(() => Collection)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class CollectionResolverBase {
  constructor(
    protected readonly service: CollectionService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Collection",
    action: "read",
    possession: "any",
  })
  async _collectionsMeta(
    @graphql.Args() args: CollectionFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Collection])
  @nestAccessControl.UseRoles({
    resource: "Collection",
    action: "read",
    possession: "any",
  })
  async collections(
    @graphql.Args() args: CollectionFindManyArgs
  ): Promise<Collection[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Collection, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Collection",
    action: "read",
    possession: "own",
  })
  async collection(
    @graphql.Args() args: CollectionFindUniqueArgs
  ): Promise<Collection | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Collection)
  @nestAccessControl.UseRoles({
    resource: "Collection",
    action: "create",
    possession: "any",
  })
  async createCollection(
    @graphql.Args() args: CreateCollectionArgs
  ): Promise<Collection> {
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        network: args.data.network
          ? {
              connect: args.data.network,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Collection)
  @nestAccessControl.UseRoles({
    resource: "Collection",
    action: "update",
    possession: "any",
  })
  async updateCollection(
    @graphql.Args() args: UpdateCollectionArgs
  ): Promise<Collection | null> {
    try {
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          network: args.data.network
            ? {
                connect: args.data.network,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Collection)
  @nestAccessControl.UseRoles({
    resource: "Collection",
    action: "delete",
    possession: "any",
  })
  async deleteCollection(
    @graphql.Args() args: DeleteCollectionArgs
  ): Promise<Collection | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Item])
  @nestAccessControl.UseRoles({
    resource: "Item",
    action: "read",
    possession: "any",
  })
  async items(
    @graphql.Parent() parent: Collection,
    @graphql.Args() args: ItemFindManyArgs
  ): Promise<Item[]> {
    const results = await this.service.findItems(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [User])
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async owner(
    @graphql.Parent() parent: Collection,
    @graphql.Args() args: UserFindManyArgs
  ): Promise<User[]> {
    const results = await this.service.findOwner(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Network, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Network",
    action: "read",
    possession: "any",
  })
  async network(@graphql.Parent() parent: Collection): Promise<Network | null> {
    const result = await this.service.getNetwork(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
