/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsDate, IsOptional, ValidateNested, IsString } from "class-validator";
import { Type } from "class-transformer";
import { CollectionCreateNestedManyWithoutNetworksInput } from "./CollectionCreateNestedManyWithoutNetworksInput";
import { CurrencyCreateNestedManyWithoutNetworksInput } from "./CurrencyCreateNestedManyWithoutNetworksInput";
@InputType()
class NetworkCreateInput {
  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  activatedDate?: Date | null;

  @ApiProperty({
    required: false,
    type: () => CollectionCreateNestedManyWithoutNetworksInput,
  })
  @ValidateNested()
  @Type(() => CollectionCreateNestedManyWithoutNetworksInput)
  @IsOptional()
  @Field(() => CollectionCreateNestedManyWithoutNetworksInput, {
    nullable: true,
  })
  collections?: CollectionCreateNestedManyWithoutNetworksInput;

  @ApiProperty({
    required: false,
    type: () => CurrencyCreateNestedManyWithoutNetworksInput,
  })
  @ValidateNested()
  @Type(() => CurrencyCreateNestedManyWithoutNetworksInput)
  @IsOptional()
  @Field(() => CurrencyCreateNestedManyWithoutNetworksInput, {
    nullable: true,
  })
  currencies?: CurrencyCreateNestedManyWithoutNetworksInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  networkSymbol!: string;
}
export { NetworkCreateInput };
